# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  updateReqs:
    runs-on: ubuntu-18.04
    env:
      working-dir: .
    steps:
      - name: Pipreq grab & run pipreqs
        run: |
          python3 -m pip install pipreqs
          pipreqs ${{env.working-dir}}
